replicaCount: 1
config:
  cluster:
    enabled: false 
  storage:
    performance_bootstrap: true
persistence:
  enabled: true
  storageClassName: "local-path"
  size: 10Gi
resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: "500m"
    memory: 512Mi
